// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTMqMcWnaWgpCx0Is0daVEGAHMWVva-E',
    appId: '1:1033038212953:android:a34f60301ed654dea76648',
    messagingSenderId: '1033038212953',
    projectId: 'poke-people',
    storageBucket: 'poke-people.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0DDdvIrwIdtEt2a-cFmSbF5o1QQFY0c',
    appId: '1:1033038212953:ios:323a5730613e411fa76648',
    messagingSenderId: '1033038212953',
    projectId: 'poke-people',
    storageBucket: 'poke-people.firebasestorage.app',
    iosBundleId: 'com.example.pokePeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0DDdvIrwIdtEt2a-cFmSbF5o1QQFY0c',
    appId: '1:1033038212953:ios:323a5730613e411fa76648',
    messagingSenderId: '1033038212953',
    projectId: 'poke-people',
    storageBucket: 'poke-people.firebasestorage.app',
    iosBundleId: 'com.example.pokePeople',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSYA3rPF3A6mVMpa_BhOF3tmhMbxZ5IY',
    appId: '1:1033038212953:web:30c44ee2cbf7f0e9a76648',
    messagingSenderId: '1033038212953',
    projectId: 'poke-people',
    authDomain: 'poke-people.firebaseapp.com',
    storageBucket: 'poke-people.firebasestorage.app',
    measurementId: 'G-SKF494Q2LK',
  );

}